### PR TITLE
Bugfix book not in database

### PR DESCRIPTION
**Pull request by ewarlock**
Added to if statement in bookstore.py get_book_by_id to set book = None if the book is not found by id in the database. 
Added while loop in main.py change_read to prompt user to re-enter book id until a valid id is entered and a book is found

addresses issue #4 
@3bdifatah

### CODE REVIEW

**Comment by claraj** [comment]
Your change in bookstore.py is the right fix - the code you added was missing in the original. This edit ensures the  `book` variable always has a value. Think about the user interface in main.py - what would the user do if they don't know the ID or decide they don't want to change read status? Remember you have a menu loop that would allow the user to try again if they enter a non-existent ID.   @3bdifatah, what do you think?

**Comment by 3bdifatah** [comment]
agree with clara user is stuck in the loop until user enters valid ID. I would just use if-else statement, if book is none just display message telling user book is not in the database and end the code. but if you want the user to end code manually:
1. edit question on ui.py line 49 to "Enter book ID or 0 to quit:"
2. change ui.py line 50 to id >= 0 so 0 is returned
3. end the code if book_id is 0 on main.py between 63-64.

**Comment by ewarlock** [comment]
Thanks for the feedback @claraj & @3bdifatah - I changed the loop to an if statement so the user can try again at the main menu if they wish, or select a different option if they changed their mind about changing the read status.

**Comment by 3bdifatah** [comment]
works better add \n before and after the error message and merge issue #4

**Review by claraj — COMMENTED** [review]
Looks good!

**Pull request merged**
