### PR TITLE
add brief program overview to readme

### PR DESCRIPTION
**Pull request by ewarlock**
Added a short description of the program, followed by a small explanation for each menu item listed when the program starts.

Addresses issue #3 
@3bdifatah

### CODE REVIEW

**Comment by 3bdifatah** [comment]
looks great, liked how you break down the menu options. I would go ahead and add the delete option as well.

**Comment by ewarlock** [comment]
@3bdifatah I went ahead and added the delete menu option to the readme. Let me know if I'm good to merge!

**Comment by 3bdifatah** [comment]
you got all now you are good to merge issue #3

**Review by claraj — COMMENTED** [review]
Looks good!

**Comment by claraj** [comment]
Also, not required for this program, but Markdown is useful for formatting text in a readme https://guides.github.com/features/mastering-markdown/

**Pull request merged**
